name: auto deploy workers
#https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/15
#trigger when tag created and match the pattern(tag name starts with v)
on:
  create:
    tags:
      - v*

env:
  scu_key: xxxxxxxxxxxxxxxxxxxx

defaults:
  run:
    shell: bash
    
jobs:
  deploy_job:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        name: clone & publish
        continue-on-error: false
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          git clone https://github.com/Akame-moe/workers
          cd workers
          cat stream.js | curl -X PUT "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/workers/scripts/stream" \
          -H  "Authorization: Bearer $CF_API_TOKEN" \
          -H "Content-Type: application/javascript" \
          --data-binary @-
          cat push.js | curl -X PUT "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/workers/scripts/push" \
          -H  "Authorization: Bearer $CF_API_TOKEN" \
          -H "Content-Type: application/javascript" \
          --data-binary @-